FROM sgw
WORKDIR /root/son-vm
RUN git pull
RUN python3 setup.py install
COPY spgw.conf /root/son-vm/server.conf
COPY spgw.sh /root/son-vm/start.sh

ENV SON_EMU_CMD "/root/son-vm/start.sh"

CMD /bin/bash

