FROM hss
WORKDIR /root/son-vm
RUN git pull
RUN python3 setup.py install
COPY hss.conf /root/son-vm/server.conf
COPY hss.sh /root/son-vm/start.sh

RUN	apt-get update && apt-get install -y \
	net-tools \
	iproute \
	iputils-ping

ENV SON_EMU_CMD "/root/son-vm/start.sh"

CMD /bin/bash

