catalogues: [personal]
description: Some description about this sample
descriptor_extension: yml
maintainer: Name, Company, Contact
name: dummy2
publish_to: [personal]
vendor: eu.sonata-nfv.package
version: '0.4'
