catalogues: [personal]
description: "vEPC service based on https://github.com/networkedsystemsIITB/NFV_LTE_EPC"
maintainer: "Steven Van Rossem, Janos Elek, Thomas Soenen"
name: "sonata-vepc-service"
publish_to: [personal]
vendor: eu.sonata-nfv.package
version: '0.4'
descriptor_extension: "yml"

