FROM epc_base:SNAPSHOT

RUN	apt-get install -y \
        lib323z1

WORKDIR / 
RUN git clone https://github.com/esnet/iperf.git   
WORKDIR iperf
RUN ./configure
RUN make
RUN make install

ENV SON_EMU_CMD "/root/son-vm/start.sh"

CMD /bin/bash

