FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -q -y git sudo wget software-properties-common make python3 libpython3-dev

WORKDIR /root
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py

WORKDIR /root
RUN git clone https://github.com/elekjani/NFV_LTE_EPC.git
WORKDIR /root/NFV_LTE_EPC/NFV_LTE_EPC-1.1/scripts
RUN bash install.sh

CMD /bin/bash
